import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import { NEXT_ACTION_REVALIDATED_HEADER } from "next/dist/client/components/app-router-headers";

import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      
    >
      <body>
        <Navbar/>

        {children}
        <Footer/>
        </body>
    </html>
  );
}
